apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo1
  template:
    metadata:
      labels:
        app: gitops-demo1
    spec:
      containers:
        - name: gitops-demo1
          image: acr7f3c6b6ae93ef0fb.azurecr.io/gitops-demo1:1
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo2
  template:
    metadata:
      labels:
        app: gitops-demo2
    spec:
      containers:
        - name: gitops-demo2
          image: acr7f3c6b6ae93ef0fb.azurecr.io/gitops-demo2:2
          ports:
            - containerPort: 5000
---          
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo1
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: gitops-demo1
---          
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo2
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 5000
  selector:
    app: gitops-demo2