apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: acraspuym7cn4yli.azurecr.io/gitops-demo:d50875dedc51a3faf6961baa7941e44cb5d771c5
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: gitops-demo