apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-demo1
  template:
    metadata:
      labels:
        app: gitops-demo1
    spec:
      containers:
        - name: gitops-demo1
          image: acr4d19045dcc6d1cc2.azurecr.io/gitops-demo1:2782e2a14a860af40a536ef622f8a5a696980f8a
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-demo2
  template:
    metadata:
      labels:
        app: gitops-demo2
    spec:
      containers:
        - name: gitops-demo2
          image: acr4d19045dcc6d1cc2.azurecr.io/gitops-demo2:2782e2a14a860af40a536ef622f8a5a696980f8a
          ports:
            - containerPort: 5000
---          
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo1
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: gitops-demo1
---          
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo2
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 5000
  selector:
    app: gitops-demo2