name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/gitops-demo1:${{ github.sha }} ./app1
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/gitops-demo1:${{ github.sha }}
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/gitops-demo2:${{ github.sha }} ./app2
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/gitops-demo2:${{ github.sha }}

  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Kubernetes manifest for gitops-demo1
        run: |
          sed -i "s|image: .*|image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/gitops-demo1:${{ github.sha }}|" deploy/k8s-manifest.yaml
  
      - name: Update Kubernetes manifest for gitops-demo2
        run: |
          sed -i "s|image: .*|image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/gitops-demo2:${{ github.sha }}|" deploy/k8s-manifest.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "277402816"
          git config --global user.email "277402816@qq.com"
          git add deploy/k8s-manifest.yaml
          git commit -m "Update Kubernetes manifest with new image tag"
          git push
